apiVersion: v1
kind: ConfigMap
metadata:
  namespace: my-webapp # namespace where this ConfigMap should be created
  name: app-config # Name of the ConfigMap we can use to reference in pods
data:
  # Example config variables
  APP_NAME: "testkube"
  APP_ENV: "production"
