apiVersion: v1 # specifies the API version . "Kind : service" gets v1 type version
kind: Service # specifies the kind of resource we are creating
metadata:
  name: postgres-service # this provide service for the database pods
spec:
  type: ClusterIP # not to be exposed outside the cluster, database should be internal use only
  selector:
    app: postgres_db # this says only the pods with the label app: postgres_db will recieve traffic from this service
  ports:
    - port: 5432 # port on which the service will be exposed inside the cluster
      targetPort: 5432 # port on which the container is listening inside the pod
      