apiVersion: v1
kind: PersistentVolumeClaim
metadata: # use to reference PVC in pods
  name: postgres-pvc # name of the PVC
spec:
  accessModes:
    - ReadWriteOnce #Volume can be mounted read/write by one node.
  resources:
    requests:
      storage: 1Gi # amount of storage requested for the PVC (giving 1 GB of storage)
