apiVersion: v1
kind: Secret
metadata: #USe to reference secret in pods
  name: db-secret
type: Opaque # type of the secret (opaque means arbitrary user-defined data)
data:
  POSTGRES_USER: ZGhhd2FsYQ==       # Base64 for 'dhawala'
  POSTGRES_PASSWORD: MTIz           # Base64 for '123'
  POSTGRES_DB: bWFuYWdlZGI=         # Base64 for 'managedb'
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vZGhhd2FsYToxMjNAcG9zdGdyZXMtc2VydmljZTo1NDMyL21hbmFnZWRi # Base64 for 'postgresql+asyncpg://dhawala:123@postgres-service:5432/managedb'