apiVersion: v1
kind: Secret
metadata: #USe to reference secret in pods
  name: db-secret
type: Opaque # type of the secret (opaque means arbitrary user-defined data)
data:
  POSTGRES_USER: ZGhhd2FsYQ==       # Base64 for 'dhawala'
  POSTGRES_PASSWORD: MTIz           # Base64 for '123'
  POSTGRES_DB: bWFuYWdlZGI=         # Base64 for 'managedb'
  DATABASE_URL: cG9zdGdyZXM6Ly9kaGF3YWxhOjEyM0BkYXRhYmFzZS1zZXJ2aWNlOjU0MzIvbWFuYWdlZGI= # Base64 for 'postgres://dhawala:123@database-service:5432/managedb'