{{- range $name, $svc := .Values.service }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
spec:
  type: {{ $svc.type }}
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.targetPort }}
{{- if eq $svc.type "NodePort" }}
      nodePort: {{ $svc.nodePort }}
{{- end }}
---
{{- end }}
{{- end }}
